export enum UserRole {
  PM = 'Project Manager',
  FEL = 'Front End Lead',
  SSE = 'Senior Software Engineer',
  SE = 'Software Engineer',
  PO = 'Product Owner',
  MANAGER = 'Manager',
  SR_MANAGER = 'Senior Manager',
  QA_LEAD = 'QA Lead',
  BACKEND_LEAD = 'Backend Lead',
  ASE = 'Associate Software Engineer',
  DEVOPS = 'DevOps',
  IOS_DEVELOPER = 'iOS Developer',
  ANDROID_DEVELOPER = 'Android Developer',
}
